
translations = {
    'dk': {
        'nav' : 'hylden med historier',
        'toast_signup_ok' : 'Tak for din tilmelding hos Vejhylden - tjek din e-mail for at bekræfte dit login.',
        'toast_login_error' : 'Bekræft venligst din e-mail for at logge ind.',
        'already_verified' : 'Brugeren er allerede blevet verificeret',
        'verification_ok' : 'Din profil er blevet verificeret. Du kan nu logge ind.',
        'verification_error' : 'Verifikation fejlet. Prøv venligst igen.',
        'email_subject' : 'Verificér din bruger hos Vejhylden.',
        'verify_link' : 'Klik venligst på nedenstående link for at verificere din bruger.',
        'forgot_password' : 'Glemt adgangskode?',

        'reset_password' : 'Nulstil din adgangskode',
        'send_reset_link' : 'Send nulstillingslink',
        'save_password' : 'Gem adgangskode',

        'reset_email_greeting' : 'Har du glemt din adgangskode til Vejhylden?',
        'reset_email_instruction' : 'Klik herunder for at vælge ny adgangskode.',




        'click_here': 'Klik her',
        'signing_up': 'for at oprette dig.',
        'thanks': 'Tak',
        'to': 'til',
        'characters': 'karakterer',
        'more_items': 'Vis mere',
        'sign_up' : 'Opret dig',
        'login' : 'Log ind',
        'logout' : 'Log ud',
        'search' : 'Søg',
        'here' : 'her',
        'admin' : 'Dit admin dashboard',
        'library' : "Biblioteker",
        'user' : 'Profiler',
        'profile' : 'Har du ikke en profil?',
        'profile_btn' : 'Profil',
        'panel_btn' : 'Panel',
        'welcome' : 'Velkommen',
        'add_item' : 'Tilføj et nyt bibliotek',
        'edit_profile' : 'Ret profiloplysninger',
        'save_changes' : 'Gem oplysninger',
        'change_password' : 'Skift adgangskode',
        'current_password' : 'Nuværende adgangskode',
        'new_password' : 'Ny adgangskode',
        'confirm_password' : 'Bekræft ny adgangskode',
        'delete_profile' : 'Slet profil',
        'user_name' : 'Navn',
        'user_lastname' : 'Efternavn',
        'user_username' : 'Brugernavn',
        'your_items' : 'Dine biblioteker',
        'profile_page' : 'Profil indstillinger',
        'name' : 'Bibliotekets navn*',
        'address' : 'Adresse*',
        'image' : 'Billede af biblioteket',
        'more_images' : 'Flere billeder af biblioteket',
        'optional' : 'Valgfrit',
        'price' : 'Indholdsværdi*',
        'create' : 'Opret bibliotek',
        'blocked' : 'Blokeret',
        'block' : 'Bloker',
        'unblock' : 'Fjern blokering',
        'active' : 'Aktiv',
        'based_on' : 'Baseret på mængde of stand af bøger',
        'info_user' : 'Brugerinformation',
        'info_item' : 'Biblioteksinformation',
        'block_user' : 'Blokering af bruger',
        'block_item' : 'Blokering af bibliotek',
    },
    'en': {
        'nav' : 'the shelf of stories',
        'toast_signup_ok' : 'Thank you for signing up to Vejhylden - check your email to confirm your login.',
        'toast_login_error' : 'Please verify your email to log in.',
        'already_verified' : 'The user has already been verified',
        'verification_ok' : 'Your account has been successfully verified. You can now log in.',
        'verification_error' : 'Verification failed. Please try again.',
        'email_subject' : 'Verify your account at Vejhylden.',
        'verify_link' : 'Please click the link below to verify your account.',
        'forgot_password' : 'Forgot password?',

        'reset_password' : 'Reset password',
        'send_reset_link' : 'Send reset link',
        'save_password' : 'Save password',

        'reset_email_greeting' : 'Forgot your password to Vejhylden?',
        'reset_email_instruction' : 'Click below to choose a new password.',




        'click_here': 'Click here',
        'signing_up': 'for signing up.',
        'thanks': 'Thank you',
        'to': 'to',
        'characters': 'characters',
        'more_items': 'Show more',
        'sign_up' : 'Sign up',
        'login' : 'Login',
        'logout' : 'Logout',
        'search' : 'Search',
        'here' : 'here',
        'admin' : 'Your admin dashboard',
        'library' : "Libraries",
        'user' : 'Users',
        'profile' : 'Don´t have a profile?',
        'profile_btn' : 'Profile',
        'panel_btn' : 'Dashboard',
        'welcome' : 'Welcome',
        'add_item' : 'Add a new library',
        'edit_profile' : 'Edit profileinformation',
        'save_changes' : 'Save changes',
        'change_password' : 'Change password',
        'current_password' : 'Current password',
        'new_password' : 'New password',
        'confirm_password' : 'Confirm new password',
        'delete_profile' : 'Delete profile',
        'user_name' : 'Name',
        'user_lastname' : 'Lastname',
        'user_username' : 'Username',
        'your_items' : 'Your libraries',
        'profile_page' : 'Profile information',
        'name' : 'Name of the library*',
        'address' : 'Address*',
        'image' : 'Picture of the library',
        'more_images' : 'More pictures of the library',
        'optional' : 'Optional',
        'price' : 'Collection value*',
        'create' : 'Create library',
        'blocked' : 'Blocked',
        'block' : 'Block',
        'unblock' : 'Unblock',
        'active' : 'Active',
        'based_on' : 'Based on the number and value of the books',
        'info_user' : 'User information',
        'info_item' : 'Library information',
        'block_user' : 'Blocking of user',
        'block_item' : 'Blocking of library',
    },
}


# defining a function to translate the keys
def translate(key: str, lan: str = 'dk') -> str:
    """
    Look up `key` in the given `lan`, falling back to key itself.
    """
    return translations.get(lan, translations['dk']) .get(key, key)


